core/urls.py
from django.contrib import admin
from django.urls import path
from core.views import index



urlpatterns = [
    path('', index, name='index'),
]

duelbola/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('hometeam.urls')),
    path('index/', include('core.urls'))
]

hometeam/urls.py
from django.urls import path
from . import views

app_name = 'hometeam'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('team/', views.team, name='team'),



]

core/models.py
from django.db import models

# Create your models here.

hometeam/models.py
from django.db import models
from django.utils.text import slugify


# Create your models here.


class Feedback(models.Model):

    feedback = models.TextField()
    
    def __str__(self):
        return self.feedback

hometeam/forms.py
from django import forms
from .models import Feedback


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = [
            'feedback'
        ]
        widgets = {
        'feedback': forms.TextInput(attrs={'class':'form-control'}),
        }

core/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

hometeam/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from .models import Feedback
from . import forms



def homepage(request):
    return render(request, 'homepage.html')

def team(request):
    if request.method == "POST" :
        form = forms.FeedbackForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('hometeam:team')

        return HttpResponse(status=302)
    else:
        form = forms.FeedbackForm()
        return render (request, 'team.html', {"form":form, "list_feedback": Feedback.objects.all()})

core/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Duel Bola</title>
</head>
<body>
    <h1>Hello World!</h1>
    <h1>Coming Soon</h1>
</body>
</html>

core/templates/navbar.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width =device-width">
    <title>DUEL BOLA</title>

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src= "https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"> </script>
    <script src= "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"> </script>
    <script src= "https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"> </script>
    <script src= "https://use.fontawesome.com/releases/v5.0.8/js/all.js"> </script>

  </head>
  <body>
    <nav class="navbar sticky-top navbar-expand-md navbar-dark my-nav">

       <a class="navbar-brand" href="#">Duel Website Page</a>

       <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
       </button>
       <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
           <ul class= "navbar-nav ml-auto">
             <li class= "nav-item" >
               <a href="{% url 'hometeam:homepage' %}" class = "nav-link">Home</a>
             </li>
             <li class= "nav-item" >
               <a href="#" class = "nav-link">Location</a>
             </li>
             <li class= "nav-item" >
               <a href="#" class = "nav-link">Game</a>
             </li>
             <li class= "nav-item" >
               <a href="#" class = "nav-link">Create Team</a>
             </li>
             <li class= "nav-item" >
               <a href="{% url 'hometeam:team' %}" class = "nav-link">Our Team</a>
             </li>

             </li>

           </ul>
       </div>
   </nav>

{% block body %}

{% endblock body %}


       <!-- Footer -->
<footer class="page-footer font-small pt-4">

  <!-- Footer Links -->
  <div class="container-fluid text-center text-md-left">

    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-6 mt-md-0 mt-3">

        <!-- Content -->
        <h5 class="text-uppercase">D U E L</h5>
        <p>Website that helps you find your opponent and a place to play</p>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none pb-3">

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

        <!-- Links -->

        <ul class="list-unstyled">
          <li>
            <a href="{% url 'hometeam:homepage' %}">Home</a>
          </li>
          <li>
            <a href="#!">Location</a>
          </li>
          <li>
            <a href="#!">Game</a>
          </li>
          <li>
            <a href="#">Create Team</a>
          </li>
          <li>
            <a href="{% url 'hometeam:team' %}">Our Team</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2018 Copyright: KD 10 Project
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

</body>


</html>

hometeam/templates/homepage.html
<!DOCTYPE html>
{% extends 'navbar.html' %}
{% load static %}

{% block body %}

      <div class="container home">

        <div class="row">

            <div class="col-6 justify-content-center align-text-center desc">
              <div class="row">
                  <h1 class= 'duelH'> D U E L</h1>
              </div>
              <div class="row">
                  <h3> Duel adalah website penyedia lawan & tempat bermain futsal atau sepak bola  </h3>
              </div>

       </div>
       <div class="col-6">
          <img class="homepage" src="{% static 'img/duel.jpg' %}" alt="Responsive Image">
         </div>
       </div>

    

       </div>

{% endblock body %}

hometeam/templates/team.html
<!DOCTYPE html>
{% extends 'navbar.html' %}
{% load static %}

{% block body %}
   <!-- Header -->
   <header class="text-center py-5 mb-4">
     <div class="container">
       <h1 class="font-weight-light text-black">Meet the Team</h1>
     </div>
   </header>

   <!-- Page Content -->
   <div class="container">
     <div class="row">
       <!-- Team Member 1 -->
       <div class="col-xl-3 col-md-6 mb-4">
         <div class="card border-0 shadow">
           <img src="{% static 'img/lado.jpg' %}" class="card-img-top" alt="...">
           <div class="card-body text-center">
             <h5 class="card-title mb-0">Lado Rayhan Najib</h5>
             <div class="card-text text-black-50">Web Developer</div>
             <ul class="list-unstyled mb-0">
               <!-- Facebook -->
               <a class="p-2 fa-lg fb-ic">
                 <i class="fab fa-facebook-f blue-text"> </i>
               </a>
               <!-- Twitter -->
               <a class="p-2 fa-lg tw-ic">
                 <i class="fab fa-twitter blue-text"> </i>
               </a>
               <!-- Instagram -->
               <a class="p-2 fa-lg ins-ic">
                 <i class="fab fa-instagram blue-text"> </i>
               </a>
             </ul>
           </div>
         </div>
       </div>
       <!-- Team Member 2 -->
       <div class="col-xl-3 col-md-6 mb-4">
         <div class="card border-0 shadow">
           <img src="{% static 'img/mumek.jpg' %}" class="card-img-top" alt="...">
           <div class="card-body text-center">
             <h5 class="card-title mb-0">Muhammad Michael</h5>
             <div class="card-text text-black-50">Web Developer</div>
             <ul class="list-unstyled mb-0">
               <!-- Facebook -->
               <a class="p-2 fa-lg fb-ic">
                 <i class="fab fa-facebook-f blue-text"> </i>
               </a>
               <!-- Twitter -->
               <a class="p-2 fa-lg tw-ic">
                 <i class="fab fa-twitter blue-text"> </i>
               </a>
               <!-- Instagram -->
               <a class="p-2 fa-lg ins-ic">
                 <i class="fab fa-instagram blue-text"> </i>
               </a>
             </ul>
           </div>
         </div>
       </div>
       <!-- Team Member 3 -->
       <div class="col-xl-3 col-md-6 mb-4">
         <div class="card border-0 shadow">
           <img src="{% static 'img/habib.jpg' %}" class="card-img-top" alt="...">
           <div class="card-body text-center">
             <h5 class="card-title mb-0">Habibullah</h5>
             <div class="card-text text-black-50">Web Developer</div>
             <ul class="list-unstyled mb-0">
               <!-- Facebook -->
               <a class="p-2 fa-lg fb-ic">
                 <i class="fab fa-facebook-f blue-text"> </i>
               </a>
               <!-- Twitter -->
               <a class="p-2 fa-lg tw-ic">
                 <i class="fab fa-twitter blue-text"> </i>
               </a>
               <!-- Instagram -->
               <a class="p-2 fa-lg ins-ic">
                 <i class="fab fa-instagram blue-text"> </i>
               </a>
             </ul>
           </div>
         </div>
       </div>
       <!-- Team Member 4 -->
       <div class="col-xl-3 col-md-6 mb-4">
         <div class="card border-0 shadow">
           <img src="{% static 'img/luqman.jpg' %}" class="card-img-top" alt="...">
           <div class="card-body text-center">
             <h5 class="card-title mb-0">Luqman</h5>
             <div class="card-text text-black-50">Web Developer</div>
             <ul class="list-unstyled mb-0">
               <!-- Facebook -->
               <a class="p-2 fa-lg fb-ic">
                 <i class="fab fa-facebook-f blue-text"> </i>
               </a>
               <!-- Twitter -->
               <a class="p-2 fa-lg tw-ic">
                 <i class="fab fa-twitter blue-text"> </i>
               </a>
               <!-- Instagram -->
               <a class="p-2 fa-lg ins-ic">
                 <i class="fab fa-instagram blue-text"> </i>
               </a>
             </ul>
           </div>
         </div>
       </div>
     </div>
     <!-- /.row -->

   </div>

   <header class="text-center mb-4">
     <div class="container">
       <h1 class="font-weight-light text-black">Feedback</h1>
     </div>
   </header>
   <form method="post">
     {% csrf_token %}
     <div class="form-group shadow-textarea">
       <!-- <textarea class="form-control z-depth-1" rows="5" placeholder="Write something here...">{{ feedback }}</textarea> -->
       {% for field in form %}
       {{field}}
       {% endfor %}

       <!-- <input type="submit" class="btn btn-primary float-right" value="Add"> -->
     </div>
     <button type="submit" name="button">Send</button>
   </form>



   <!-- /.container -->
{% endblock body %}